# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class LogLevelEnum(str, enum.Enum):
    """
    An enumeration.
    """

    VERBOSE = "verbose"
    CONCISE = "concise"

    def visit(self, verbose: typing.Callable[[], T_Result], concise: typing.Callable[[], T_Result]) -> T_Result:
        if self is LogLevelEnum.VERBOSE:
            return verbose()
        if self is LogLevelEnum.CONCISE:
            return concise()
