# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OrderByEnum(str, enum.Enum):
    """
    An enumeration.
    """

    UPDATED_AT = "updated_at"
    CREATED_AT = "created_at"

    def visit(self, updated_at: typing.Callable[[], T_Result], created_at: typing.Callable[[], T_Result]) -> T_Result:
        if self is OrderByEnum.UPDATED_AT:
            return updated_at()
        if self is OrderByEnum.CREATED_AT:
            return created_at()
