# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.get_transforms_response import GetTransformsResponse
from ....types.get_transforms_with_params_response import GetTransformsWithParamsResponse

GetTransformsV1TransformsGetResponse = typing.Union[GetTransformsWithParamsResponse, GetTransformsResponse]
